application: nullonerror
version: 1
runtime: python27
api_version: 1
threadsafe: off

builtins:
- appstats: on

libraries:
- name: jinja2
  version: "2.6"

handlers:
- url: /favicon\.ico
  static_files: static/img/favicon.ico
  upload: static/img/favicon\.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /static
  static_dir: static

- url: /.*
  script: views.py

